api_keys:
  newsapi: "YOUR_NEWS_API_KEY"
  openai: "YOUR_OPENAI_API_KEY"

news_defaults:
  category: "general"
  country: "us"
  page_size: 10

recommendation:
  num_articles: 5

logging:
  level: "INFO"
  format: "[%(asctime)s]: %(message)s"
